### ISSUE TITLE
no main manifest attribute, in swagger-diff-1.2.2.jar

### ISSUE THREAD

**Issue by shwetrai** [Sayi/swagger-diff#37]
used mvn package to build the jar. Once build the jar, trying to run the following command
java -jar swagger-diff-1.2.2.jar --help

But getting error - 
no main manifest attribute, in swagger-diff-1.2.2.jar

**Comment by MichaelKittlitz** [comment]
Same story over here. Have not conclusion why this happens yet.

java -jar swagger-diff-1.2.2.jar -old /home/software/swagger-diff/swagger_v0p9.json -new /home/software/swagger-diff/swagger_v0.91.json -v 2.0 -output-mode html > diff_v0.9_v0.91.html

Leads to:
put-mode html > diff_v0.9_v0.91.html
no main manifest attribute, in swagger-diff-1.2.2.jar

The HTML-File is 0 Bytes long and therefore empty.

=== 

$ java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

=== 

Version 1.2.1 has the same result.

=== 

Tried the asset of https://github.com/Sayi/swagger-diff/releases (swagger-diff.jar 10.1 MB)

leads to a different result though:

put-mode html > diff_v0.9_v0.91.html
Exception in thread "main" java.lang.RuntimeException: cannot read api-doc from spec.
        at com.deepoove.swagger.diff.SwaggerDiff.<init>(SwaggerDiff.java:122)
        at com.deepoove.swagger.diff.SwaggerDiff.compare(SwaggerDiff.java:81)
        at com.deepoove.swagger.diff.SwaggerDiff.compareV2(SwaggerDiff.java:53)
        at com.deepoove.swagger.diff.cli.CLI.run(CLI.java:66)
        at com.deepoove.swagger.diff.cli.CLI.main(CLI.java:51)

=== 

Tried again with an older JAVA-Version:

java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

"C:\Program Files\Java\jdk1.8.0_241\bin\java.exe" -jar swagger-diff-1.2.2.jar -old swagger_v0p9.json -new swagger_v0.91.json
kein Hauptmanifestattribut, in swagger-diff-1.2.2.jar

**Comment by frascu** [comment]
Clone my fork repository and execute this command:
```bash
mvn package
```
Then you can use `swagger-diff-1.2.2-jar-with-dependencies.jar` to execute the command line tools.

**Comment by frascu** [comment]
It is enough to download:
https://github.com/Sayi/swagger-diff/releases/download/v1.2.2/swagger-diff.jar
It is executable and it works correctly.

**Comment by owlengineer** [comment]
I still getting this error

`java -jar swagger-diff-new.jar -old http://petstore.swagger.io/v2/swagger.json -new http://petstore.swagger.io/v2/swagger.json -v 2.0 -output-mode html > diff.html
Exception in thread "main" java.lang.RuntimeException: cannot read api-doc from spec.
	at com.deepoove.swagger.diff.SwaggerDiff.<init>(SwaggerDiff.java:122)
	at com.deepoove.swagger.diff.SwaggerDiff.compare(SwaggerDiff.java:81)
	at com.deepoove.swagger.diff.SwaggerDiff.compareV2(SwaggerDiff.java:53)
	at com.deepoove.swagger.diff.cli.CLI.run(CLI.java:66)
	at com.deepoove.swagger.diff.cli.CLI.main(CLI.java:51)
`

**Comment by gowtham758550** [comment]
I'm also getting the same error
```
java --version
openjdk 24.0.2 2025-07-15
OpenJDK Runtime Environment (build 24.0.2+12-54)
OpenJDK 64-Bit Server VM (build 24.0.2+12-54, mixed mode, sharing)
```

<img width="1525" height="250" alt="Image" src="https://github.com/user-attachments/assets/c8b86f2f-5147-4fda-a2db-140371acf232" />


Edit: It is not working only when i try remote files.
